### ISSUE TITLE
Batch load

### ISSUE THREAD

**Issue by gertschouten** [IBM/nzgo#24]
Hi,

Is it possible to batch load with this driver?
If so, how?

**Comment by shabbir10july** [comment]
@gertschouten : By 'batch load' do you mean netezza external table load which loads/insets data into tables from flat file ?

**Comment by gertschouten** [comment]
Hi yes. And if not than any other form of batch insert with less round-trips.

**Comment by shabbir10july** [comment]
Yes, we can load data into table from flat file. 
In below example, we are loading data/rows from flat file **C:\Users\ShabbirMohammad\Desktop\Project\et1.txt** (this can be linux path also) to netezza user table **t2**. The file has column delimited with symbol **|**. Please note you need to specify **remotesource 'golang'** in the query while using this feature from go driver.

```
result, err := db.Exec("insert into t2 select * from external 'C:\\Users\\ShabbirMohammad\\Desktop\\Project\\et1.txt' (C1 , C2 , C3 , C4 , C5 , C6 , C7 , C8 , C9 , C10 , C11 , C12 , DATE_PROD , TIME_PROD, INTERVAL_PROD ,TIMESTMP ,TIMETZ_PROD, C18) using ( remotesource 'golang' delimiter '|' )")
	if err != nil {
		fmt.Println("row was not inserted successfully", err, result)
	} else {
		rows, _ := result.RowsAffected()
		fmt.Println(rows, "row inserted successfully")
	}
```

**Comment by gertschouten** [comment]
Thanks Mohommed. That's what I was looking for. I will try this now.

**Comment by gertschouten** [comment]
This works Mohammad. Thanks. No problems on the server side. Gets inserted as expected there.
On the client i get panic though:
panic: Error opening file: "open /tmp\\TESTTABLE_TEST.ADMIN.TESTDATABASE.nzlog:....." [recovered]

This is independent of the elog.LogPath settings right? 
I tried with an elog.LogPath and without,

Is the server side somehow returning log information that the client needs to receive?

I see the stacktrace points to this line in conn.go 1126:
if err != nil { // file open failed
		elog.Fatalf(chopPath(funName()), "Error opening file: %q", err)
		status = false
	}

Do you have any idea how I can fix that? Probably just some path settings. I am on windows, running from visual code.

**Comment by shabbir10july** [comment]
Yes this is independent of  elog.LogPath.
This is log file on external table.
You probably need to provide log directory in external table query (in using clause). For e.g.: LogDir 'C\users\..'. 
By default, it takes /tmp which is failing on windows.
https://www.ibm.com/support/knowledgecenter/SSULQD_7.2.1/com.ibm.nz.load.doc/r_load_logdir.html

**Comment by gertschouten** [comment]
Thanks again. Works perfect now. Was missing using LogDir as you explained.
