### ISSUE TITLE
Lengths of query result's columns don't show up well.

### ISSUE THREAD

**Issue by aniket-s-kulkarni** [IBM/nzgo#36]
In `nzpy` (or odbc) a query's result set reports the max lengths of each columns of the result set before reading / fetching the entire result set.

```python
In [4]: c = nzpy.connect(database="system", host=os.environ["NZ_HOST"], user="admin", password="password", port=5480)

In [5]: cr = c.cursor()

In [6]: cr.execute("SELECT Database, Owner FROM _v_database")
Out[6]: <nzpy.core.Cursor at 0x10b61e100>

In [17]: cr.description
Out[17]:
[(b'DATABASE', 19, None, None, None, None, None),
 (b'OWNER', 19, None, None, None, None, None)]
```

Doing the same in nzgo returns a 0 

```shell
2021/07/14 18:15:21 sql.go:273: ci=0 name=Schema len=0:false dlen=0:0:false d=NAME
2021/07/14 18:15:21 sql.go:273: ci=1 name=Name len=0:false dlen=0:0:false d=NAME
2021/07/14 18:15:21 sql.go:273: ci=2 name=Type len=0:false dlen=0:0:false d=NAME
2021/07/14 18:15:21 sql.go:273: ci=3 name=Owner len=0:false dlen=0:0:false d=NAME
```

The golang code snippet looks like this - 

```go
        rows, err := db.Query(sq)
	if err != nil {
		return err
	}

	if rows != nil {
		defer rows.Close()
		for {
			cts, err := rows.ColumnTypes()
			for ci, ct := range cts {
				l, ok := ct.Length()
				p, s, pok := ct.DecimalSize()
				log.Printf("ci=%d name=%s len=%d:%t dlen=%d:%d:%t d=%s\n", ci, ct.Name(), l, ok, p, s, pok, ct.DatabaseTypeName())
			}
```

**Comment by sandippawar1412** [comment]
@aniket-s-kulkarni 
Is this working code snippet? golang part? 
Could you please provide complete example? 

Getting errors like
`rows.Length undefined (type *sql.Rows has no field or method Length)`

**Comment by aniket-s-kulkarni** [comment]
> @aniket-s-kulkarni
> Is this working code snippet? golang part?
> Could you please provide complete example?
> 
> Getting errors like
> `rows.Length undefined (type *sql.Rows has no field or method Length)`

@sandippawar1412 - there was a typo, I have corrected it above.

**Comment by abhishekjog** [comment]
https://github.com/IBM/nzgo/pull/45 fixed this.
