### ISSUE TITLE
nzgo logger Initialize method's receiver is passed by value

### ISSUE THREAD

**Issue by aniket-s-kulkarni** [IBM/nzgo#47]
[Initialize() method's receiver is passed by value](https://github.com/IBM/nzgo/blob/master/logger.go#L49); so after initialize the logger itself doesn't change. It does set the `log.Logger` instance correctly, so the changes take effect, but `NZLogger` instance remains unchanged. 

```go
// here's a test program
package main

import (
	"fmt"

	"github.com/IBM/nzgo/v12"
)

func main() {
	var nzl nzgo.NZLogger
	fmt.Printf("Before Initialize(): %+v\n", nzl)
	nzl.Initialize("DEBUG", "/tmp/nzlog", "stdout")
	fmt.Printf("After Initialize(): -- nothing changed --  %+v\n", nzl)
}
```

This what it shows on running
```
Before Initialize(): {LogLevel: LogPath: AdditionalLogFile:}
---------------- IBM PDA Log -----------------
----------------------------------------------
After Initialize(): -- nothing changed --  {LogLevel: LogPath: AdditionalLogFile:}
```

[Initialize() method's receiver should be a pointer](https://github.com/IBM/nzgo/blob/master/logger.go#L49); something like this - 

```go
// in logger.go
var elog *NZLogger = &NZLogger{}

// the Initialize method ..
func (elog *NZLogger) Initialize(logLevel, logPath, additionalLogFile string) { 
....
```

With this nothing else needs to change.

**Comment by sandippawar1412** [comment]
https://github.com/IBM/nzgo/pull/48
