### ISSUE TITLE
Connection errors are indecipherable from other regular errors

### ISSUE THREAD

**Issue by aniket-s-kulkarni** [IBM/nzgo#50]
In `.Open()` method, if the destination was stopped or unreachable, prior to #46, `.Open` used to return a system error - `syscall.ECONNREFUSED`

```go
conn, err := sql.Open(.....)
if errors.Is(err, syscall.ECONNREFUSED) {
   // take action if destination is stopped or unreachable
```

This doesn't work and now one has to resort to string parsing to find this out. The error returned is a generic one 

```
FATAL] v12.(*Connector).open 548 : dial tcp 127.0.0.1:5480: connect: connection refused
```

For well known cases, we should have standard well defined error that can be checked without needing to scrape error message.

**Comment by sandippawar1412** [comment]
https://github.com/IBM/nzgo/pull/51
