### ISSUE TITLE
Use platform Separator to Locate conf.json config file 

### ISSUE THREAD

**Issue by jwiss** [IBM/nzgo#8]
Generalize the conn.go init() method to use platform separators. See: 
https://github.com/IBM/nzgo/blob/master/conn.go#L268

Specifically,   
  fname = fname + "\\src\\github.com\\IBM\\nzgo\\config\\conf.json"
Should be   
  fname = fname + filepath.FromSlash("/src/github.com/IBM/nzgo/config/conf.json")   
Otherwise, we are seeing an error in linux containers.

Longer term, it would be nice to programmatically initialize the logging and allow a user to redirect logging output. Probably by allowing the user to specify an io.Writer (as with Go's logger). Then one could, e.g. direct log output where a logging infrastructure has log forwarding, log rotation, etc.  I don’t see such capabilities in the existing code. For now, the above change is simple and does not impact the existing interface.

@tomuboyd12

**Comment by shabbir10july** [comment]
We have incorporated the suggested changes. Closing the issue.
